name: water_quality_app
description: A Water Quality Assessment Mobile App with WQI calculation, PDF reports, and cloud storage
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.1.0
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.12.0
  path: ^1.8.3
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
